name: mdspage
description: MDS Page.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  url_launcher: ^6.0.20
  animate_do: ^2.1.0
  fancy_shimmer_image: ^2.0.1+1
  platform: ^3.1.0
  font_awesome_flutter: ^9.2.0
  qlevar_router: ^1.5.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/preview-ss1.png
    - assets/images/preview-ss2.png
    - assets/images/preview-ss3.png
    - assets/images/ss1.png
    - assets/images/ss2.png
    - assets/images/ss3.png
